### PR TITLE
Sub-objects are never indexed when explicit es_indexed: true is used. This fixes that. Fixes jamescarr/mongoosastic#69.

### LINKED ISSUE #69: Not indexing nested fields
Hey,
if I dont use es_indexed = true in my schema, everything works, all fields are indexed.

If I use them, all fields that are nested, like below, do not work.

{
object: {
     field1: {type: String, es_indexed: true}
}

"object" field is not indexed, and its not available as source as well.

Do you guys have experienced this as well? Thanks.

### PR DESCRIPTION
**Pull request by jeresig**
Sub-objects are never indexed when explicit es_indexed: true is used. This fixes that. Fixes jamescarr/mongoosastic#69.

The solution isn't fantastic. Unfortunately sub-objects are _always_ indexed now once `es_indexed: true` is used. However if you have at least one `es_indexed: true` in the sub-object then the other properties won't come through. Probably good enough for now.

### CODE REVIEW

**Comment by jeresig** [comment]
Huh - while this does improve the situation (it now generates the correct mapping). It seemingly still does not index the objects correctly. I'm investigating now.

File: lib/mapping-generator.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ function getMapping(cleanTree, prefix) {
     // Check if field was explicity indexed, if not keep track implicitly
     if(value.es_indexed) {
       hasEs_index = true;
-    } else {
+    } else if (value.type) {
```
Comment (jeresig) [inline lib/mapping-generator.js:43]: This makes it so that objects are no longer automatically tacked on to the `implicitFields` list.

File: lib/mapping-generator.js [hunk 2]
```diff
@@ -99,14 +99,15 @@ function getCleanTree(tree, paths, prefix) {
       type = '',
       value = {};
 
-  delete tree.id;
```
Comment (jeresig) [inline lib/mapping-generator.js:102]: These were bad - it appears as if properties were being deleted from the schema itself. No need to do that, we can just skip the properties in the loop.

File: lib/mongoosastic.js [hunk 3]
```diff
@@ -4,7 +4,7 @@ var elastical = require('elastical')
   , events    = require('events');
 
 module.exports = function elasticSearchPlugin(schema, options){
-  var indexedFields = getIndexedFields(schema)
+  var mapping = getMapping(schema)
```
Comment (jeresig) [inline lib/mongoosastic.js:7]: We now iterate over the mapping rather than this custom `getIndexedFields` (which gave us a value that didn't really match the correct mapping).

File: lib/serialize.js [hunk 4]
```diff
@@ -1,39 +1,26 @@
 module.exports = serialize;
 
-function serialize(model, indexedFields) {
-  var serializedForm = {}
-    , indexedFields = indexedFields?indexedFields:[];
+function serialize(model, mapping) {
```
Comment (jeresig) [inline lib/serialize.js:3]: `serialize()` is now recursive and requires that the mapping exists. Sub-objects are now handled correctly, as a result.

**Comment by jeresig** [comment]
(I'm writing up some indexing tests now.)

**Comment by jeresig** [comment]
@taterbase Ok, I think we're good for a review now!

File: lib/serialize.js (hunk 4 above)
Comment (taterbase) [inline lib/serialize.js:3]: Oh man, sooooo good.

**Comment by taterbase** [comment]
This PR is radsauce, thanks for the effort. One of the tests need updating but I'll rectify that.

**Comment by jeresig** [comment]
@taterbase Fantastic, happy to help! And thank you for the land! (I may have some other improvements coming along as I'm looking to use this in production on one of my sites.) I'll be in touch.

**Comment by taterbase** [comment]
Looking forward to it!
